apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: {{ .Values.deployment.name }}
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.deployment.name }}-deployment
  targetCPUUtilizationPercentage: 40
